var jsProject=function(){var b=this;b.MODULE="jsProject";b["debugger"]=null;b.values=null;b.ajax=null;b.events=null;b.functionsModule=null;b.jsonToElementHtmlModule=null;b.constructed=!1;b.debuggerConstructed=!1;b.construct=function(){if(b.constructed)return!1;jsProject.debug=function(){};b.constructed=!0;b.values=new jsProject.valuesModule;b.events=new jsProject.eventsModule;b.ajax=new jsProject.ajaxModule;b.functions=new jsProject.functionsModule;b.jsonToElementHtmlModule=new jsProject.jsonToElementHtmlModule};
b.debugOn=function(a,c){a&&!b.debuggerConstructed&&(jsProject["debugger"]=new jsProject.debugModule(c),b.debuggerConstructed=!0);a?jsProject["debugger"].active(!0):b.debuggerConstructed&&jsProject["debugger"].active(!1)};return{construct:function(){b.construct()},debugOn:function(a,c){b.debugOn(a,c)}}}();
(function(b){b.ajaxModule=function(){var a=this;a.MODULE="ajaxModule";a.debugOn=!0;a.nextProcesId=0;a.errorCount=0;a.maxRecalls=0;a.processes={};a.downloadCallback=null;a.header=null;a.construct=function(){a.debug("construct");b.securePost=a.securePost;b.secureDownload=a.secureDownload;b.post=a.post};a.post=function(c,d,b,e){e||(d.procesId=a.nextProcesId,a.debug("new proces: "+d.procesId+" url: "+c+" subject: "+d.subject),b={id:a.nextProcesId++,url:c,isSecure:!1,recallCount:0,data:d,callback:b},a.processes[b.id]=
b);$.ajax({type:"POST",async:!0,url:c,data:d,dataType:"json",success:function(c){a.debug("ajax succes");a.succes(c)},error:function(c,d,b){a.errorCount++;console.log("ajax error");$.each(c,function(c,d){a.debug("ajax failed jqXHR:"+d);console.log(d)});a.debug("ajax failed textStatus:"+d);a.debug("ajax failed errorThrown:"+b);a.handleErrors()}})};a.securePost=function(c,d,b,e,f){f?(a.debug("recall secure post url: "+c),a.debug("recall proces: "+b.procesId)):(b.procesId=a.nextProcesId,b.token=d,a.debug("new secure proces: "+
b.procesId+" url: "+c+" subject: "+b.subject),d={id:a.nextProcesId++,url:c,data:b,isSecure:!0,recallCount:0,callback:e},a.processes[d.id]=d);$.ajax({type:"POST",async:!0,url:c,data:b,dataType:"json",success:function(c){a.succes(c)},error:function(c,d,b){a.errorCount++;console.log("ajax error");$.each(c,function(a,c){console.log(c)});a.debug("-------- ajax failed ---------"+d);a.debug("textStatus:"+d);a.debug("errorThrown:"+b);a.debug("-------- end ajax failed ---------"+d);a.handleErrors()}})};a.secureDownload=
function(a,d,b){b.token=d;var c=new XMLHttpRequest;c.open("POST",a,!0);c.responseType="arraybuffer";c.onload=function(){if(200===this.status){var a="",d=c.getResponseHeader("Content-Disposition");d&&-1!==d.indexOf("attachment")&&(d=/filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/.exec(d),null!==d&&d[1]&&(a=d[1].replace(/['"]/g,"")));d=c.getResponseHeader("Content-Type");d=new Blob([this.response],{type:d});if("undefined"!==typeof window.navigator.msSaveBlob)window.navigator.msSaveBlob(d,a);else{var b=window.URL||
window.webkitURL,g=b.createObjectURL(d);a?(d=document.createElement("a"),"undefined"===typeof d.download?window.location=g:(d.href=g,d.download=a,document.body.appendChild(d),d.click())):window.location=g;setTimeout(function(){b.revokeObjectURL(g)},100)}}};c.setRequestHeader("Content-type","application/x-www-form-urlencoded");c.send($.param(b))};a.downloadSucces=function(c){a.downloadCallback(c);a.downloadCallback=null};a.succes=function(c){a.debug("succes");null===c.procesId?(console.log("procesId = null error "),
$.each(c,function(a,c){console.log(a+": "+c)})):(a.debug("succes proces: "+c.procesId),a.processes[c.procesId].callback(c.result),delete a.processes[c.procesId]);a.handleErrors()};a.handleErrors=function(){if(0!==a.errorCount&&Object.keys(a.processes).length===a.errorCount){a.errorCount=0;var c=!1;$.each(a.processes,function(d,b){b.recallCount<a.maxRecalls&&(c=!0,a.recall(d,b))});if(!c){var d={criticalError:"dataConnectionFailed"};$.each(a.processes,function(a,c){c.callback(d)})}}};a.recall=function(c,
d){d.recallCount++;d.isSecure?a.securePost(d.url,d.data.token,d.data,d.callback,!0):a.post(d.url,d.data,d.callback,!0)};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.checkEmailSyntaxFunction=function(){var a=this;a.MODULE="checkEmailSyntaxFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.checkEmailSyntax=a.checkEmailSyntax};a.checkEmailSyntax=function(a){return/^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,64})$/.test(a)};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.dateObjectToDbDateFunction=function(){var a=this;a.MODULE="dateObjectToDbDateFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.dateObjectToDbDate=a.dateObjectToDbDate};a.dateObjectToDbDate=function(a){var c=a.year;c+=b.pad(a.month,"0",2);return c+=b.pad(a.day,"0",2)};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.dateObjectToTextFunction=function(){var a=this;a.MODULE="dateObjectToTextFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.dateObjectToText=a.dateObjectToText};a.dateObjectToText=function(a){var c=b.pad(a.day,"0",2);c=c+"-"+b.pad(a.month,"0",2);return c=c+"-"+a.year};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.dbDateToDateObjectFunction=function(){var a=this;a.MODULE="dbDateToDateObjectFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.dbDateToDateObject=a.dbDateToDateObject};a.dbDateToDateObject=function(a){return{day:parseInt(a.slice(6,8)),month:parseInt(a.slice(4,6)),year:parseInt(a.slice(0,4))}};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.debugModule=function(a){var c=this;c.MODULE="debugModule";c.debugOn=!0;c.options=a;c.lineCounter=0;c.construct=function(){var a='<div id="jsProjectDebugDiv" style=" position:absolute; '+(" top: "+c.options.top+"px; ");a+=" left: "+c.options.left+"px;";a+=" z-index: "+c.options.zIndex+";";a=a+' border: lightblue 1px groove;  border-radius: 5px; "><div id="jsProjectDebugDivDragHandle" style=" cursor:move;  width:100%;  height:20px;  background-color:green; "></div><div id="jsProjectDebugDivContent" style=" line-height: 1.2em;  overflow: auto; '+
(" width: "+c.options.width+"px; ");a+=" height: "+c.options.height+"px;";a+=' background-color:black;color:white; "></div></div>';$(document.body).append(a);b.debug=c.debug;$("#jsProjectDebugDivDragHandle").mouseenter(function(){c.dragHandleMouseIn()});$("#jsProjectDebugDivDragHandle").mouseout(function(){c.dragHandleMouseOut()});$("#jsProjectDebugDivDragHandle").mousedown(function(a){c.dragHandleMouseClick(a)})};c.dragHandleMouseIn=function(){$("#jsProjectDebugDivDragHandle").css("background-color",
"lightgreen")};c.dragHandleMouseOut=function(){$("#jsProjectDebugDivDragHandle").css("background-color","green")};c.dragHandleMouseClick=function(a){c.lastPosition={x:a.pageX,y:a.pageY};$(document).on("mousemove",function(a){c.move(a)});$(document).on("mouseup",function(a){c.up(a)})};c.move=function(a){c.positionChange={x:0,y:0};c.positionChange.y=c.lastPosition.y-a.pageY;c.positionChange.x=c.lastPosition.x-a.pageX;var d=parseFloat($("#jsProjectDebugDiv").offset().top)-parseFloat(c.positionChange.y),
b=parseFloat($("#jsProjectDebugDiv").offset().left)-parseFloat(c.positionChange.x);0>d&&(d=0);0>b&&(b=0);$("#jsProjectDebugDiv").css("top",d);$("#jsProjectDebugDiv").css("left",b);c.lastPosition={x:a.pageX,y:a.pageY}};c.up=function(a){$(document).off("mousemove");$(document).off("mouseup")};c.active=function(a){a?($("#jsProjectDebugDivContent").prepend(b.pad(c.lineCounter,"0",2)+"-Debugger started<br/>"),c.lineCounter++,c.lineCounter%=10,$("#jsProjectDebugDivContent").show()):($("#jsProjectDebugDivContent").prepend(b.pad(c.lineCounter,
"0",2)+"-Debugger stopped<br/>"),c.lineCounter++,c.lineCounter%=10,$("#jsProjectDebugDivContent").hide());c.debugOn=a};c.debug=function(a){c.debugOn&&($("#jsProjectDebugDivContent").prepend(b.pad(c.lineCounter,"0",2)+"-"+a+"<br/>"),c.lineCounter++,c.lineCounter%=10)};c.construct();return{active:function(a){c.active(a)}}}})(jsProject);
(function(b){b.elementIsVisibleFunction=function(){var a=this;a.MODULE="elementIsVisibleFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.elementIsVisible=a.elementIsVisible};a.elementIsVisible=function(c,d){var b=$("#"+c).offset().top,e=$("#"+d).offset().top,f=$("#"+d).height();a.debug("elementTop: "+b);a.debug("parentTop: "+e);a.debug("screenHeight: "+f);if(b>f||b<e)return a.debug("item not visible"),!1;a.debug("item visible");
return!0};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.eventsModule=function(){var a=this;a.MODULE="eventsModule";a.debugOn=!1;a.events={};a.construct=function(){a.debug("construct ");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.subscribeToEvent=a.subscribe;b.unSubscribeFromEvent=a.unSubscribe;b.callEvent=a.call};a.subscribe=function(c,d){a.debug("subscribe: "+c);a.events[c]||(a.events[c]=[]);a.events[c].push({callback:d})};a.unSubscribe=function(c,d){a.debug("unSubscribe: "+c);if(a.events[c])for(var b=a.events[c].length-
1;0<=b;b--)a.events[c][b].callback===d&&a.events[c].splice(b,1)};a.call=function(c,d){a.debug("call: "+c);if(a.events[c]){for(var b=[],e=0;e<a.events[c].length;e++)b.push(a.events[c][e].callback);for(e=0;e<b.length;e++)b[e](d)}};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.functionsModule=function(){var a=this;a.MODULE="functionsModule";a.debugOn=!1;a.getJsonValueFunction=null;a.elementIsVisibleFunction=null;a.scrollElementFunction=null;a.getElementPositionFunction=null;a.padfunction=null;a.checkEmailSyntaxFunction=null;a.xorStringFunction=null;a.dateObjectToDbDateFunction=null;a.dateObjectToTextFunction=null;a.dbDateToDateObjectFunction=null;a.getNextDayFunction=null;a.getPreviousDayFunction=null;a.getTodayDbDateFunction=null;a.getTodayTextFunction=
null;a.getWeekFunction=null;a.textToDateObjectFunction=null;a.hexStringToRgbFunction=null;a.hsvToRgbFunction=null;a.rgbIsRgbFunction=null;a.rgbToHexStringFunction=null;a.rgbToHsvFunction=null;a.rgbToStringFunction=null;a.stringToRgbFunction=null;a.construct=function(){a.debug("construct");a.addCommonFunctions();a.addTextFunctions();a.addDateFunctions();a.addColorFunctions()};a.addCommonFunctions=function(){a.getJsonValueFunction=new b.getJsonValueFunction;a.getElementPositionFunction=new b.getElementPositionFunction;
a.elementIsVisibleFunction=new b.elementIsVisibleFunction;a.scrollElementFunction=new b.scrollElementFunction};a.addTextFunctions=function(){a.padfunction=new b.padFunction;a.checkEmailSyntaxFunction=new b.checkEmailSyntaxFunction;a.xorStringFunction=new b.xorStringFunction};a.addDateFunctions=function(){a.dateObjectToDbDateFunction=new b.dateObjectToDbDateFunction;a.dateObjectToTextFunction=new b.dateObjectToTextFunction;a.dbDateToDateObjectFunction=new b.dbDateToDateObjectFunction;a.getNextDayFunction=
new b.getNextDayFunction;a.getPreviousDayFunction=new b.getPreviousDayFunction;a.getTodayDbDateFunction=new b.getTodayDbDateFunction;a.getTodayTextFunction=new b.getTodayTextFunction;a.getWeekFunction=new b.getWeekFunction;a.textToDateObjectFunction=new b.textToDateObjectFunction};a.addColorFunctions=function(){a.stringToRgbFunction=new b.stringToRgbFunction;a.hexStringToRgbFunction=new b.hexStringToRgbFunction;a.hsvToRgbFunction=new b.hsvToRgbFunction;a.rgbIsRgbFunction=new b.rgbIsRgbFunction;a.rgbToHexStringFunction=
new b.rgbToHexStringFunction;a.rgbToHsvFunction=new b.rgbToHsvFunction;a.rgbToStringFunction=new b.rgbToStringFunction};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.getElementPositionFunction=function(){var a=this;a.MODULE="getElementPositionFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.getElementPosition=a.getElementPosition};a.getElementPosition=function(a){for(var c={top:0,left:0},b=document.getElementById(a);b;)c.top+=b.offsetTop+b.clientTop,c.left+=b.offsetLeft+b.clientLeft,b=b.offsetParent;for(b=document.getElementById(a);b;)"BODY"!==b.tagName&&(c.top-=
b.scrollTop||0,c.left-=b.scrollLeft||0),b=b.parentNode;return c};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.getJsonValueFunction=function(){var a=this;a.MODULE="getJsonValueFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.getJsonValue=a.getJsonValue};a.getJsonValue=function(c,b){a.debug("get json value");for(var d=0,e=c,f=0;f<b.length;f++)if($.isArray(e)){a.debug("found array"+b[d]);var h=b[d].split("="),k=h[0],l=h[1];$.each(e,function(a,c){c[k]===l&&(e=c,d++)})}else a.debug("found object"+b[d]),e=e[b[d]],
d++;if(d===b.length)return a.debug("value found: "+e),e;console.log("error getJsonValue object not found ");console.log("object"+JSON.stringify(c));console.log("search array"+JSON.stringify(b))};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.getNextDayFunction=function(){var a=this;a.MODULE="getNextDayFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.getNextDay=a.getNextDay};a.getNextDay=function(a){var c=new Date(a.year,parseInt(a.month)-1,a.day);c.setHours(0,0,0,0);c.setDate(c.getDate()+1);a.year=c.getFullYear().toString();a.month=c.getMonth()+1;a.day=c.getDate();return a};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();
return{}}})(jsProject);
(function(b){b.getPreviousDayFunction=function(){var a=this;a.MODULE="getPreviousDayFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.getPreviousDay=a.getPreviousDay};a.getPreviousDay=function(a){var c=new Date(a.year,parseInt(a.month)-1,a.day);c.setHours(0,0,0,0);c.setDate(c.getDate()-1);a.year=c.getFullYear().toString();a.month=c.getMonth()+1;a.day=c.getDate();return a};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+
" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.getTodayDbDateFunction=function(){var a=this;a.MODULE="getTodayDbDateFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.getTodayDbDate=a.getTodayDbDate};a.getTodayDbDate=function(){var a=new Date,d=a.getFullYear().toString(),g=b.pad(a.getMonth()+1,"0",2);a=b.pad(a.getDate(),"0",2);return d+g+a};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.getTodayTextFunction=function(){var a=this;a.MODULE="getTodayTextFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.getTodayText=a.getTodayText};a.getTodayText=function(){var a=new Date,d=a.getFullYear().toString(),g=b.pad(a.getMonth()+1,"0",2);return b.pad(a.getDate(),"0",2)+"-"+g+"-"+d};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.getWeekFunction=function(){var a=this;a.MODULE="getWeekFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.getWeek=a.getWeek};a.getWeek=function(a){a=new Date(a.year,a.month,a.day);a.setHours(0,0,0,0);a.setDate(a.getDate()+3-(a.getDay()+6)%7);var c=new Date(a.getFullYear(),0,4);return 1+Math.round(((a.getTime()-c.getTime())/864E5-3+(c.getDay()+6)%7)/7)};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+
" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.hexStringToRgbFunction=function(){var a=this;a.MODULE="hexStringToRgbFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.hexStringToRgb=a.hexStringToRgb};a.hexStringToRgb=function(a){var c=parseInt(a.substring(0,2),16);isNaN(c)&&(c=0);var b=parseInt(a.substring(2,4),16);isNaN(b)&&(b=0);a=parseInt(a.substring(4,6),16);isNaN(a)&&(a=0);return{r:c,g:b,b:a}};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+
" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.hsvToRgbFunction=function(){var a=this;a.MODULE="hsvToRgbFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.hsvToRgb=a.hsvToRgb};a.hsvToRgb=function(a){var c=a.h,b=a.s,e={r:0,g:0,b:0};a=Math.round(a.v/100*255);if(null===c)return e.r=a,e.g=a,e.b=a,e;c/=60;b/=100;var f=Math.floor(c),h=Math.round(a*(1-b));c=Math.round(a*(1-b*(f%2?c-f:1-(c-f))));switch(f){case 1:return e.r=c,e.g=a,e.b=h,e;case 2:return e.r=
h,e.g=a,e.b=c,e;case 3:return e.r=h,e.g=c,e.b=a,e;case 4:return e.r=c,e.g=h,e.b=a,e;case 5:return e.r=a,e.g=h,e.b=c,e;default:return e.r=a,e.g=c,e.b=h,e}};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.jsonToElementHtmlModule=function(){var a=this;a.MODULE="jsonToElementHtmlModule";a.debugOn=!1;a.closeElements=["a","div","svg","iframe"];a.properties="id name type value src href target title size width height maxlength rowspan colspan".split(" ");a.styles={zIndex:"z-index",position:"position","float":"float",clear:"clear",top:"top",left:"left",display:"display",overflow:"overflow",overflowX:"overflow-x",overflowY:"overflow-y",cursor:"cursor",background:"background",backgroundColor:"background-color",
backgroundRepeat:"background-repeat",backgroundPosition:"background-position",backgroundSize:"background-size",color:"color",minimumWidth:"min-width",maximumWidth:"max-width",minimumHeight:"min-height",maximumHeight:"max-height",styleWidth:"width",styleHeight:"height",fontFamily:"font-family",fontSize:"font-size",lineHeight:"line-height",letterSpacing:"letter-spacing",fontWeight:"font-weight",textAlign:"text-align",verticalAlign:"vertical-align",margin:"margin",marginTop:"margin-top",marginLeft:"margin-left",
marginRight:"margin-right",marginBottom:"margin-bottom",padding:"padding",paddingTop:"padding-top",paddingLeft:"padding-left",paddingRight:"padding-right",paddingBottom:"padding-bottom",imageUrl:"background-image",transformOrigin:"transform-origin",boxShadow:"box-shadow"};a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.jsonToElementHtml=a.jsonToElementHtml};a.jsonToElementHtml=function(c){var b="<"+c.element;b+=a.addProperties(c);
b+=a.addStyle(c);b+=">";c.text&&(b+=c.text);0<=a.closeElements.indexOf(c.element)&&(b+="</"+c.element+">");return b};a.addProperties=function(c){var b="";$.each(a.properties,function(a,d){void 0!==c[d]&&(b+=" "+d+'="'+c[d],"number"===typeof c[d]&&(b+="px;"),b+='"')});c.readOnly&&(b+=" readOnly ");c.checked&&(b+=" checked ");return b};a.addStyle=function(c){var b="";b+=' style="';$.each(a.styles,function(a,d){void 0!==c[a]&&(b+=d+" : "+c[a],"number"===typeof c[a]&&(b+="px"),b+=";")});b+=a.addBorder(c);
return b+='"'};a.addBorder=function(c){var b="";void 0!==c.border&&(b=b+" border: "+a.getBorderHtml(c));void 0!==c.borderTop&&(b=b+" border-top: "+a.getBorderHtml(c));void 0!==c.borderLeft&&(b=b+" border-left: "+a.getBorderHtml(c));void 0!==c.borderRight&&(b=b+" border-right: "+a.getBorderHtml(c));void 0!==c.borderBottom&&(b=b+" border-bottom: "+a.getBorderHtml(c));void 0!==c.borderRadius&&(b=b+" border-radius: "+c.borderRadius,b+=";");return b};a.getBorderHtml=function(a){var c=""+a.borderWidth;
c=c+" "+a.borderColor;c=c+" "+a.borderStyle;return c+";"};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.padFunction=function(){var a=this;a.MODULE="padFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.pad=a.pad};a.pad=function(a,b,g){for(a=a.toString();a.length<g;)a=b+a;return a};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.rgbIsRgbFunction=function(){var a=this;a.MODULE="rgbIsRgbFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.rgbIsRgb=a.rgbIsRgb};a.rgbIsRgb=function(a,b){return a.r===b.r&&a.g===b.g&&a.b===b.b?!0:!1};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.rgbToHexStringFunction=function(){var a=this;a.MODULE="rgbToHexStringFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.rgbToHexString=a.rgbToHexString};a.rgbToHexString=function(a){var c=""+b.pad(a.r.toString(16),"0",2);c+=b.pad(a.g.toString(16),"0",2);return c+=b.pad(a.b.toString(16),"0",2)};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.rgbToHsvFunction=function(){var a=this;a.MODULE="rgbToHsvFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.rgbToHsv=a.rgbToHsv};a.rgbToHsv=function(a){var c={h:0,s:0,v:0},b=JSON.parse(JSON.stringify(a));b.r/=255;b.g/=255;b.b/=255;var e=Math.min(Math.min(b.r,b.g),b.b);a=Math.max(Math.max(b.r,b.g),b.b);var f=a-e;if(0===f)return c.h=null,c.s=0,c.v=100*a,c;b=b.r===e?3+(b.b-b.g)/f:b.g===e?5+(b.r-b.b)/
f:1+(b.g-b.r)/f;c.h=60*(6===b?0:b);c.s=f/a*100;c.v=100*a;return c};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.rgbToStringFunction=function(){var a=this;a.MODULE="rgbToStringFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.rgbToString=a.rgbToString};a.rgbToString=function(a){var b="rgb( "+Math.round(a.r);b=b+","+Math.round(a.g);b=b+","+Math.round(a.b);return b+" )"};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.scrollElementFunction=function(){var a=this;a.MODULE="scrollElementFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.scrollElement=a.scrollElement};a.scrollElement=function(b,d){var c=$("#"+b).offset().top;var e=$("#"+d).offset().top,f=$("#"+d).height();a.debug("elementTop: "+c);a.debug("parentTop: "+e);a.debug("screenHeight: "+f);c>f?(a.debug("item not visible"),c=document.getElementById(b),c.scrollIntoView(!1)):
c<e?(a.debug("item not visible"),c=document.getElementById(b),c.scrollIntoView(!0)):a.debug("item visible")};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.stringToRgbFunction=function(){var a=this;a.MODULE="stringToRgbFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.stringToRgb=a.stringToRgb};a.stringToRgb=function(a){var b=a.indexOf("(");b++;var c=a.indexOf(","),e=parseInt(a.slice(b,c));b=c+1;c=a.indexOf(",",b);var f=parseInt(a.slice(b,c));b=c+1;c=a.indexOf(")",b);a=parseInt(a.slice(b,c));return{r:e,g:f,b:a}};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+
" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.textToDateObjectFunction=function(){var a=this;a.MODULE="textToDateObjectFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.textToDateObject=a.textToDateObject};a.textToDateObject=function(a){return{day:parseInt(a.slice(0,2)),month:parseInt(a.slice(3,5)),year:parseInt(a.slice(6,10))}};a.debug=function(c){a.debugOn&&b.debug(a.MODULE+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.valuesModule=function(){var a=this;a.MODULE="valuesModule";a.debugOn=!1;a.groups={};a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.addValue=a.addValue;b.addValueList=a.addValueList;b.getValue=a.getValue;b.setValue=a.setValue};a.addValue=function(b,d,g){a.debug("addValue: id:"+b+", group, :"+d+", value:"+g);void 0===a.groups[d]&&(a.groups[d]={});void 0!==a.groups[d][b]?a.debug("add value warning value already exists id: "+
b):a.groups[d][b]=g};a.addValueList=function(b,d){a.debug("addValueList: group, :"+d);for(var c in b)a.addValue(c,d,b[c])};a.getValue=function(b,d){a.debug("getValue: id:"+b+", group, :"+d);if(void 0!==a.groups[d][b])return a.groups[d][b];a.debug("get value error value not found id: "+b);return!1};a.setValue=function(b,d,g){a.debug("setValue: id:"+b+", group, :"+d+", value:"+g);void 0!==a.groups[d][b]?a.groups[d][b]=g:a.debugOn&&a.debug("set value error value not found id: "+b)};a.debug=function(c){a.debugOn&&
b.debug(a.FUNCTION+" "+c)};a.construct();return{}}})(jsProject);
(function(b){b.xorStringFunction=function(){var a=this;a.MODULE="xorStringFunction";a.debugOn=!1;a.construct=function(){a.debug("construct");a.addApplicationsExtensions()};a.addApplicationsExtensions=function(){b.xorString=a.xorString};a.xorString=function(b,d){for(var c="",e=0;e<d.length;e++)c=e<b.length?c+a.xorChar(b[e],d[e]):c+a.xorChar(" ",d[e]);return c};a.xorChar=function(a,b){var c=parseInt(a.charCodeAt(0)),d=parseInt(b.charCodeAt(0));return String.fromCharCode(c^d)};a.debug=function(c){a.debugOn&&
b.debug(a.FUNCTION+" "+c)};a.construct();return{}}})(jsProject);